### ISSUE TITLE
Fails when reusing a workflow

### ISSUE THREAD

**Issue by avdv** [cgrindel/gha_join_jobs#52]
In https://github.com/tweag/rules_nixpkgs/blob/master/.github/workflows/release.yaml we reuse the https://github.com/tweag/rules_nixpkgs/blob/master/.github/workflows/workflow.yaml:
```yaml
jobs:
  tests:
    # Do only release when CI succeeds.
    uses: ./.github/workflows/workflow.yaml
```
which contains:
```yaml
jobs:
  all_ci_tests:
    runs-on: ubuntu-latest
    needs:
      - test-nixpkgs
      - test-examples
    if: ${{ always() }}
    steps:
      - uses: cgrindel/gha_join_jobs@794a2d117251f22607f1aab937d3fd3eaaf9a2f5 # v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
```
this is failing with (see https://github.com/tweag/rules_nixpkgs/actions/runs/8459023869/job/23189535156):
```
Unsuccessful jobs:
[
  {
    "id": 23189535156,
    "name": "tests / all_ci_tests",
    "status": "in_progress",
    "conclusion": null
  }
]
Error: Process completed with exit code 1.
```

The reason is that `GITHUB_JOB` always contains the job id (the name after `jobs.<...>`), but this is matched against the `name` of the jobs returned from Github API.

If one does not set a name with `jobs.<id>.name` explicitly, the name will be identical to the id. So usually this works.

But when re-using a job from another workflow, the name will change to `<name> / <id>` as can be seen in the error above.

**Comment by prednaz** [comment]
wow, thanks for debugging this one, @avdv!

**Comment by cgrindel** [comment]
I did some research. [We aren't the only ones affected by this.](https://github.com/orgs/community/discussions/8945)

Right now, the best idea that I have is to have the reusable workflow to take a parameter which will be the "workflow ID" (i.e., the name used by the caller). This will then need to be passed to `gha_join_jobs`.

Excerpt from the top-level workflow
```yaml
jobs:
  child_workflow:
    # Do only release when CI succeeds.
    uses: ./.github/workflows/workflow.yaml
    with:
      workflow_id: "child_workflow"   # <= This matches the name of the job.
```

Excerpt from the child workflow.

```yaml
workflow_call:
  inputs:
    worklfow_id:
      default: ''
      type: string

jobs:
  # ...
  all_ci_tests:
    runs-on: ubuntu-latest
    needs:
      - test-nixpkgs
      - test-examples
    if: ${{ always() }}
    steps:
      - uses: cgrindel/gha_join_jobs@794a2d117251f22607f1aab937d3fd3eaaf9a2f5 # v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow_id: ${{ input.workflow_id }}   # <= Pass the worklfow_id
```

This is very brittle. However, I don't have any other good ideas.

@avdv If I added the `workflow_id` to the action, would you be OK with us adding a `workflow_id` to the CI workflow yaml in `rules_nixpkgs`?
